# Generated by Django 3.2.8 on 2021-12-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(verbose_name=models.DecimalField(decimal_places=3, max_digits=10)),
        ),
    ]
