# Generated by Django 3.2.8 on 2021-12-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotecnico',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
