# Generated by Django 3.2.8 on 2021-12-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formularioregistro',
            old_name='nom_usuario',
            new_name='nombre_usuario',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='nom_usuario',
            new_name='nombre_usuario',
        ),
    ]
