# Generated by Django 3.2.8 on 2021-12-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20211207_0228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
